org: jimbo4350
app: minimal-example-rds
service: serverless-minimal-example-rds

provider:
  name: aws
  runtime: haskell
  region: ap-southeast-2
  timeout: 100

functions:
  apigw:
    handler: serverless-haskell-example.apigw
    events:
      - http:
          path: item/test
          method: get

plugins:
  - serverless-haskell
  - serverless-offline
